# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "doesfacebook"
  s.version = "1.0.0.pre1"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Awexome Labs"]
  s.date = "2012-10-11"
  s.description = "Lightweight gem enables your Rails application to quickly and simply integrate with Facebook"
  s.email = "engineering@awexomelabs.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG.rdoc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "ROADMAP.rdoc",
    "Rakefile",
    "VERSION",
    "doesfacebook.gemspec",
    "lib/doesfacebook.rb",
    "lib/doesfacebook/config.rb",
    "lib/doesfacebook/configuration.rb",
    "lib/doesfacebook/controls.rb",
    "lib/doesfacebook/filters.rb",
    "lib/doesfacebook/middleware.rb",
    "lib/doesfacebook/session.rb",
    "lib/generators/doesfacebook/config/config_generator.rb",
    "lib/generators/doesfacebook/config/templates/doesfacebook.yml",
    "lib/helpers/does_facebook_helper.rb"
  ]
  s.homepage = "http://github.com/awexome/doesfacebook"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.17"
  s.summary = "Lightweight gem enables your Rails application to quickly and simply integrate with Facebook"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.1.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<rspec>, [">= 2.11.0"])
    else
      s.add_dependency(%q<rails>, [">= 3.1.0"])
      s.add_dependency(%q<bundler>, ["~> 1.1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<rspec>, [">= 2.11.0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.1.0"])
    s.add_dependency(%q<bundler>, ["~> 1.1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<rspec>, [">= 2.11.0"])
  end
end

