# AWEXOME LABS
# DoesFacebook Config

module DoesFacebook
  module Config
    
    protected
    
    # Load app configuration by Facebook callback path with a fallback to config
    # defined with name matching our current environment:
    def facebook_config
      app_settings = all_facebook_config.find do |app_name, settings|
        (settings["ssl_callback_url"] || settings["callback_url"]).match(/https?:\/\/#{request.host}/)
      end
      if app_settings
        app_name, app_config = app_settings
        if app_config
          Rails.logger.info("  Facebook configuration for app \"#{app_name}\" loaded via request to host #{request.host}")
          return @@facebook_config = HashWithIndifferentAccess.new(app_config)
        end
      end
      
      @@facebook_config = HashWithIndifferentAccess.new(all_facebook_config[Rails.env])
      unless @@facebook_config.blank?
        Rails.logger.info("  Facebook configuration loaded for app based on environment \"#{Rails.env}\"")
      else
        Rails.logger.warn("  Facebook configuration could not be found. doesfacebook.yml has no app for host #{request.host}")
        Rails.logger.warn("  Facebook configuration can be generated by running \"rails generate does_facebook:config\"")
      end
      
      return @@facebook_config
    end
    
      
    # Load configuration from YAML file for all environments:
    def all_facebook_config
      return @@all_facebook_config if @all_facebook_config
      config_file = File.join(Rails.root, "config", "doesfacebook.yml")
      if File.exist?(config_file)
        return @@all_facebook_config ||= YAML.load(File.open( config_file ))
      end
    end
        
  end
end # DoesFacebook

